spring.application.name=Recepten Radar
spring.datasource.url=jdbc:mysql://localhost:3306/receptenradar
spring.datasource.username=receptUser
spring.datasource.password=receptUserPW

spring.jpa.hibernate.ddl-auto=create-drop
